#!/usr/bin/env bash
set -euo pipefail

RELEASE_TAG='v0.11.12-rc.1'
RELEASE_TITLE='Epic DashTune 0.11.12 RC1'
PUBLIC_SOURCE_COMMIT='24ace519ab249178f00972828b7bf20ac2df5580'
PRIVATE_SOURCE_COMMIT='6d705d5ae3078a2ade377c51e8fe10b680374f1a'
ACCEPTED_SOURCE_BASELINE='13797491070fc32fd18c2bc52e137130a129ce5a'
PRIVATE_CI_HEAD='15aac93bf8d8cb385bd2cd3eaf6dd0fd43b63af5'
PRIVATE_CI_RUN='30794624036'
PRIVATE_ARTIFACT_ID='8848426854'
PRIVATE_ARTIFACT_ZIP_SHA256='596ed23ab5ba0761bfe1a7b71de457c6c57f72bc73b168cbcd3927911726a972'
PRIVATE_INPUT_APK_SHA256='0a8529841409e12a90b3070457f9698fc806a1fb92980b2f55958f61213475ce'
PATCH_SHA256='09f9bc13582574d6753e1e8e427f850e1c65dad4dd37d4fd08b8c4bd0979b0e7'
APK_SHA256='8747d162b426ce94f517750fa37907512bdfaeba81baf12098850dc1e3a3c5c2'
EXPECTED_SIGNER_SHA256='d92dae5e61910fae171af41f615c00685e5e3e6909512f2a0429df0805db8f76'
EXPECTED_DASHBOARD_BLOB='4579fef38d08a493cd009316fe0e37384fc90680'
EXPECTED_RUNTIME_BLOB='216fbc885611200c16ec2fe2bb3ae99856f6ff32'
EXPECTED_WHATSNEW_BLOB='305b37475de43da7f9991882f380f3d6cae267b1'
APK_NAME='Epic-DashTune-0.11.12-rc.1.apk'
REPORT_NAME='Epic-DashTune-0.11.12-rc.1-verification.txt'
CHECKSUM_NAME='Epic-DashTune-0.11.12-rc.1.apk.sha256'

if gh release view "$RELEASE_TAG" --repo "$GITHUB_REPOSITORY" >/dev/null 2>&1; then
  echo "Release $RELEASE_TAG already exists" >&2
  exit 1
fi
if git ls-remote --exit-code --tags "https://github.com/$GITHUB_REPOSITORY.git" "refs/tags/$RELEASE_TAG" >/dev/null 2>&1; then
  echo "Tag $RELEASE_TAG already exists" >&2
  exit 1
fi

sudo apt-get update -qq
sudo apt-get install -y -qq zstd unzip
SDK_ROOT="${ANDROID_HOME:-${ANDROID_SDK_ROOT:-}}"
test -n "$SDK_ROOT"
if test -d "$SDK_ROOT/build-tools/34.0.0"; then
  BUILD_TOOLS="$SDK_ROOT/build-tools/34.0.0"
else
  BUILD_TOOLS="$(find "$SDK_ROOT/build-tools" -mindepth 1 -maxdepth 1 -type d | sort -V | tail -1)"
fi
test -n "$BUILD_TOOLS"
APKSIGNER="$BUILD_TOOLS/apksigner"
AAPT="$BUILD_TOOLS/aapt"
ZIPALIGN="$BUILD_TOOLS/zipalign"
test -x "$APKSIGNER"
test -x "$AAPT"
test -x "$ZIPALIGN"
BUILD_TOOLS_VERSION="$(basename "$BUILD_TOOLS")"

PRIVATE_ARTIFACT_URL="$(cat release_payload/private-artifact-url.txt)"
test -n "$PRIVATE_ARTIFACT_URL"
rm -rf private-carrier controlled-assets
mkdir -p private-carrier/unpacked controlled-assets
curl --fail --location --retry 3 --retry-all-errors "$PRIVATE_ARTIFACT_URL" -o private-carrier/artifact.zip
echo "$PRIVATE_ARTIFACT_ZIP_SHA256  private-carrier/artifact.zip" | sha256sum -c -
unzip -q private-carrier/artifact.zip -d private-carrier/unpacked
BASE_APK="$(find private-carrier/unpacked -type f -name '*.apk' -print -quit)"
test -n "$BASE_APK"
echo "$PRIVATE_INPUT_APK_SHA256  $BASE_APK" | sha256sum -c -

cat release_payload/rc1.patch.zst.b64.part-* | base64 --decode > rc1.patch.zst
echo "$PATCH_SHA256  rc1.patch.zst" | sha256sum -c -
zstd --decompress --patch-from="$BASE_APK" rc1.patch.zst -o "$APK_NAME"
echo "$APK_SHA256  $APK_NAME" | sha256sum -c -
printf '%s  %s\n' "$APK_SHA256" "$APK_NAME" > "$CHECKSUM_NAME"

"$APKSIGNER" verify --verbose --print-certs "$APK_NAME" | tee apksigner.txt
grep -Eq '^Verified using v1 scheme .*: false$' apksigner.txt
grep -Eq '^Verified using v2 scheme .*: true$' apksigner.txt
grep -Eq '^Number of signers: 1$' apksigner.txt
SIGNER="$(awk -F': ' '/Signer #1 certificate SHA-256 digest:/ {print tolower($2); exit}' apksigner.txt)"
test "$SIGNER" = "$EXPECTED_SIGNER_SHA256"

"$AAPT" dump badging "$APK_NAME" | tee aapt-badging.txt
grep -Fq "package: name='com.buttonbox.ble.jz' versionCode='1114' versionName='0.11.12-stale1-jz'" aapt-badging.txt
grep -Fq "sdkVersion:'26'" aapt-badging.txt
grep -Fq "targetSdkVersion:'34'" aapt-badging.txt

"$ZIPALIGN" -c -P 16 -v 4 "$APK_NAME" | tee zipalign.txt
unzip -t "$APK_NAME" | tee unzip-test.txt

unzip -p "$APK_NAME" assets/dashboard_lab.html > controlled-assets/dashboard_lab.html
unzip -p "$APK_NAME" assets/dashboard_runtime_snapshot.js > controlled-assets/dashboard_runtime_snapshot.js
unzip -p "$APK_NAME" assets/whatsnew.txt > controlled-assets/whatsnew.txt
test "$(git hash-object controlled-assets/dashboard_lab.html)" = "$EXPECTED_DASHBOARD_BLOB"
test "$(git hash-object controlled-assets/dashboard_runtime_snapshot.js)" = "$EXPECTED_RUNTIME_BLOB"
test "$(git hash-object controlled-assets/whatsnew.txt)" = "$EXPECTED_WHATSNEW_BLOB"

{
  echo 'Epic DashTune 0.11.12 RC1 verification report'
  echo "Generated by GitHub Actions using official Android build-tools $BUILD_TOOLS_VERSION"
  echo
  echo 'RESULT'
  echo '------'
  echo 'Official Android apksigner verification: PASS'
  echo 'Package/version identity: PASS'
  echo 'Continuity signer identity: PASS'
  echo 'APK Signature Scheme v2: PASS'
  echo 'ZIP integrity: PASS'
  echo 'Page-aware alignment: PASS'
  echo 'Controlled packaged asset equality: PASS'
  echo 'Physical SM-T500 / Mega144H7 acceptance: NOT RUN in this publication gate'
  echo
  echo 'ARTIFACT'
  echo '--------'
  echo "Filename: $APK_NAME"
  echo "SHA-256: $APK_SHA256"
  echo "Size: $(stat -c '%s' "$APK_NAME") bytes"
  echo
  echo 'APPLICATION IDENTITY'
  echo '--------------------'
  grep '^package:' aapt-badging.txt
  grep '^sdkVersion:' aapt-badging.txt
  grep '^targetSdkVersion:' aapt-badging.txt
  echo
  echo 'SIGNATURE VERIFICATION'
  echo '----------------------'
  cat apksigner.txt
  echo
  echo 'SOURCE / BUILD PROVENANCE'
  echo '-------------------------'
  echo 'Private source repository: PJawZK/EpicDash-JZ'
  echo "Private authoritative commit: $PRIVATE_SOURCE_COMMIT"
  echo "Accepted application-source baseline: $ACCEPTED_SOURCE_BASELINE"
  echo "Exact private CI assembly head: $PRIVATE_CI_HEAD"
  echo "Private Android-quality run: $PRIVATE_CI_RUN"
  echo "Private workflow artifact ID: $PRIVATE_ARTIFACT_ID"
  echo "Private workflow artifact ZIP SHA-256: $PRIVATE_ARTIFACT_ZIP_SHA256"
  echo "Exact private CI input APK SHA-256: $PRIVATE_INPUT_APK_SHA256"
  echo "Continuity-signing delta SHA-256: $PATCH_SHA256"
  echo "Public curated-source tag target: $PUBLIC_SOURCE_COMMIT"
  echo
  echo 'CONTROLLED ASSET GIT-BLOB SHA-1'
  echo '-------------------------------'
  echo "assets/dashboard_lab.html: $EXPECTED_DASHBOARD_BLOB"
  echo "assets/dashboard_runtime_snapshot.js: $EXPECTED_RUNTIME_BLOB"
  echo "assets/whatsnew.txt: $EXPECTED_WHATSNEW_BLOB"
  echo
  echo 'ZIP ALIGNMENT'
  echo '-------------'
  cat zipalign.txt
  echo
  echo 'RELEASE STATUS'
  echo '--------------'
  echo 'This artifact is an official release candidate and GitHub pre-release.'
  echo 'It is not yet the accepted field APK. Separate physical acceptance is required.'
} > "$REPORT_NAME"

gh release create "$RELEASE_TAG" \
  --repo "$GITHUB_REPOSITORY" \
  --target "$PUBLIC_SOURCE_COMMIT" \
  --title "$RELEASE_TITLE" \
  --notes-file release_payload/RELEASE_NOTES.md \
  --prerelease \
  "$APK_NAME" \
  "$CHECKSUM_NAME" \
  "$REPORT_NAME"

gh release view "$RELEASE_TAG" --repo "$GITHUB_REPOSITORY" --json tagName,name,isPrerelease,isDraft,url,assets

gh api --method DELETE "repos/$GITHUB_REPOSITORY/git/refs/heads/$GITHUB_HEAD_REF" || true
