'use strict';
const assert=require('assert');
const fs=require('fs');
const store=fs.readFileSync('app/src/main/java/com/buttonbox/ble/TunerPermanentProjectStore.kt','utf8');
const surface=fs.readFileSync('app/src/main/java/com/buttonbox/ble/T4TuningWorkspaceSurface.kt','utf8');
const activity=fs.readFileSync('app/src/main/java/com/buttonbox/ble/DashboardLabActivity.kt','utf8');
const project=fs.readFileSync('app/src/main/assets/t4_tuning_workspace_project_state.js','utf8');
const base=fs.readFileSync('app/src/main/assets/t4_tuning_workspace.js','utf8');
const telemetry=fs.readFileSync('app/src/main/assets/t4_tuning_workspace_telemetry_controls.js','utf8');
const crash=fs.readFileSync('app/src/main/java/com/buttonbox/ble/CrashTraceStore.kt','utf8');
const gradle=fs.readFileSync('app/build.gradle.kts','utf8');

assert.ok(!store.includes('primeBootstrapCacheAsync(context, snapshot'), 'live TuneSnapshot must not prime giant saved workspace');
assert.ok(store.includes('tunerOfflineProjectionDeferred'), 'deferred offline projection metric missing');
assert.ok(store.includes('savedWorkspace(profile, snapshot)'), 'offline saved-project authority must remain available on demand');
assert.ok(surface.includes('fun requestPermanentProject(view: WebView?): Boolean'), 'native on-demand permanent-project request missing');
const installStart=surface.indexOf('private fun installCombinedScript');
const deliveryStart=surface.indexOf('private fun tryRegisterCandidateDelivery',installStart);
const installSection=surface.slice(installStart,deliveryStart);
assert.ok(!installSection.includes('loadPermanentProjectAsync(view, token)'), 'Tuner install must not eagerly load permanent project');
assert.ok(surface.includes('tunerPermanentProjectDeferredAtInstall'), 'deferred-install metric missing');
assert.ok(activity.includes('fun requestPermanentTunerProject(): String'), 'JS/native lazy project bridge missing');
assert.ok(activity.includes('UsbEcuManager.State.HANDSHAKE')&&activity.includes('UsbEcuManager.State.STREAMING'), 'offline project request must defer while USB live path is active');
assert.ok(!project.includes('t4ProjectSessionFallback'), 'render-time full workspace fallback clone must remain removed');
assert.ok(!project.includes('function t4ProjectCaptureLive'), 'live workspace must not be deep-cloned after render');
assert.ok(project.includes('requestPermanentTunerProject'), 'offline JS must request persisted project on demand');
assert.ok(project.includes('t4ProjectReleasePermanentForLive'), 'large saved project must be releasable after live takeover');
assert.ok(base.includes('host.getBoundingClientRect()'), 'curve graph must use measured container geometry');
assert.ok(base.includes("viewBox:'0 0 '+graphWidth+' '+graphHeight"), 'curve SVG must not retain fixed desktop viewBox');
assert.ok(!base.includes("viewBox:'0 0 1000 520'"), 'fixed 1000x520 curve canvas returned');
assert.ok(telemetry.includes('TUNER_UI_1207_MEASURED_CURVE_GEOMETRY')&&telemetry.includes('new ResizeObserver'), 'curve post-layout resize observer missing');
assert.ok(crash.includes('Thread.setDefaultUncaughtExceptionHandler')&&crash.includes('throwable.printStackTrace'), 'uncaught crash breadcrumb missing');
assert.ok(activity.includes('CrashTraceStore.install(this)')&&activity.includes('"lastUncaughtCrash"'), 'diagnostic crash trace integration missing');
assert.ok(gradle.includes('versionCode = 1207'));
assert.ok(gradle.includes('versionName = "0.12.5-tuner-live-lazy-jz"'));
for(const forbidden of ['bulkTransfer(','controlTransfer(','requestBurn']) assert.ok(!project.includes(forbidden),'project state gained raw/write authority: '+forbidden);
console.log('Tuner 1207 live-lazy/crash/curve characterization passed');
